name: w2c-letsencrypt-esxi

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create VIB
        run: /bin/bash ./build/build.sh

      - name: Store VIB
        uses: actions/upload-artifact@v2
        with:
          name: w2c-letsencrypt-esxi
          path: |
            artifacts/w2c-letsencrypt-esxi.vib
            artifacts/w2c-letsencrypt-esxi-offline-bundle.zip
          if-no-files-found: error

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build artifacts
        uses: actions/download-artifact@v2
        with:
          name: w2c-letsencrypt-esxi

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: w2c-letsencrypt-esxi
          files: |
            w2c-letsencrypt-esxi.vib
            w2c-letsencrypt-esxi-offline-bundle.zip
